# Generated by Django 5.0.1 on 2024-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
