# Generated by Django 5.0.3 on 2024-03-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Notes',
        ),
    ]
