# Generated by Django 5.0.3 on 2024-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_rename_location_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
