# Generated by Django 5.0.3 on 2024-03-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_notes_title_alter_notes_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='title',
            new_name='name',
        ),
    ]
