# Generated by Django 5.0.3 on 2024-03-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_rename_title_notes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
